# Generated by Django 4.2.7 on 2023-11-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
